// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account.proto

#ifndef PROTOBUF_account_2eproto__INCLUDED
#define PROTOBUF_account_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_account_2eproto();
void protobuf_AssignDesc_account_2eproto();
void protobuf_ShutdownFile_account_2eproto();

class LoginReq;
class LoginResp;
class CreateRoleReq;
class PRole;
class PUpRole;

// ===================================================================

class LoginReq : public ::google::protobuf::Message {
 public:
  LoginReq();
  virtual ~LoginReq();

  LoginReq(const LoginReq& from);

  inline LoginReq& operator=(const LoginReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginReq& default_instance();

  void Swap(LoginReq* other);

  // implements Message ----------------------------------------------

  LoginReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginReq& from);
  void MergeFrom(const LoginReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string account = 1;
  inline bool has_account() const;
  inline void clear_account();
  static const int kAccountFieldNumber = 1;
  inline const ::std::string& account() const;
  inline void set_account(const ::std::string& value);
  inline void set_account(const char* value);
  inline void set_account(const char* value, size_t size);
  inline ::std::string* mutable_account();
  inline ::std::string* release_account();
  inline void set_allocated_account(::std::string* account);

  // required string key = 2;
  inline bool has_key() const;
  inline void clear_key();
  static const int kKeyFieldNumber = 2;
  inline const ::std::string& key() const;
  inline void set_key(const ::std::string& value);
  inline void set_key(const char* value);
  inline void set_key(const char* value, size_t size);
  inline ::std::string* mutable_key();
  inline ::std::string* release_key();
  inline void set_allocated_key(::std::string* key);

  // required int32 areaId = 3;
  inline bool has_areaid() const;
  inline void clear_areaid();
  static const int kAreaIdFieldNumber = 3;
  inline ::google::protobuf::int32 areaid() const;
  inline void set_areaid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:LoginReq)
 private:
  inline void set_has_account();
  inline void clear_has_account();
  inline void set_has_key();
  inline void clear_has_key();
  inline void set_has_areaid();
  inline void clear_has_areaid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* account_;
  ::std::string* key_;
  ::google::protobuf::int32 areaid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_account_2eproto();
  friend void protobuf_AssignDesc_account_2eproto();
  friend void protobuf_ShutdownFile_account_2eproto();

  void InitAsDefaultInstance();
  static LoginReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginResp : public ::google::protobuf::Message {
 public:
  LoginResp();
  virtual ~LoginResp();

  LoginResp(const LoginResp& from);

  inline LoginResp& operator=(const LoginResp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginResp& default_instance();

  void Swap(LoginResp* other);

  // implements Message ----------------------------------------------

  LoginResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginResp& from);
  void MergeFrom(const LoginResp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // optional .PRole role = 2;
  inline bool has_role() const;
  inline void clear_role();
  static const int kRoleFieldNumber = 2;
  inline const ::PRole& role() const;
  inline ::PRole* mutable_role();
  inline ::PRole* release_role();
  inline void set_allocated_role(::PRole* role);

  // @@protoc_insertion_point(class_scope:LoginResp)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_role();
  inline void clear_has_role();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::PRole* role_;
  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_account_2eproto();
  friend void protobuf_AssignDesc_account_2eproto();
  friend void protobuf_ShutdownFile_account_2eproto();

  void InitAsDefaultInstance();
  static LoginResp* default_instance_;
};
// -------------------------------------------------------------------

class CreateRoleReq : public ::google::protobuf::Message {
 public:
  CreateRoleReq();
  virtual ~CreateRoleReq();

  CreateRoleReq(const CreateRoleReq& from);

  inline CreateRoleReq& operator=(const CreateRoleReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateRoleReq& default_instance();

  void Swap(CreateRoleReq* other);

  // implements Message ----------------------------------------------

  CreateRoleReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateRoleReq& from);
  void MergeFrom(const CreateRoleReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 spriteId = 1;
  inline bool has_spriteid() const;
  inline void clear_spriteid();
  static const int kSpriteIdFieldNumber = 1;
  inline ::google::protobuf::int32 spriteid() const;
  inline void set_spriteid(::google::protobuf::int32 value);

  // required string roleName = 2;
  inline bool has_rolename() const;
  inline void clear_rolename();
  static const int kRoleNameFieldNumber = 2;
  inline const ::std::string& rolename() const;
  inline void set_rolename(const ::std::string& value);
  inline void set_rolename(const char* value);
  inline void set_rolename(const char* value, size_t size);
  inline ::std::string* mutable_rolename();
  inline ::std::string* release_rolename();
  inline void set_allocated_rolename(::std::string* rolename);

  // @@protoc_insertion_point(class_scope:CreateRoleReq)
 private:
  inline void set_has_spriteid();
  inline void clear_has_spriteid();
  inline void set_has_rolename();
  inline void clear_has_rolename();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* rolename_;
  ::google::protobuf::int32 spriteid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_account_2eproto();
  friend void protobuf_AssignDesc_account_2eproto();
  friend void protobuf_ShutdownFile_account_2eproto();

  void InitAsDefaultInstance();
  static CreateRoleReq* default_instance_;
};
// -------------------------------------------------------------------

class PRole : public ::google::protobuf::Message {
 public:
  PRole();
  virtual ~PRole();

  PRole(const PRole& from);

  inline PRole& operator=(const PRole& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PRole& default_instance();

  void Swap(PRole* other);

  // implements Message ----------------------------------------------

  PRole* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PRole& from);
  void MergeFrom(const PRole& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 roleId = 1;
  inline bool has_roleid() const;
  inline void clear_roleid();
  static const int kRoleIdFieldNumber = 1;
  inline ::google::protobuf::int64 roleid() const;
  inline void set_roleid(::google::protobuf::int64 value);

  // required string roleName = 2;
  inline bool has_rolename() const;
  inline void clear_rolename();
  static const int kRoleNameFieldNumber = 2;
  inline const ::std::string& rolename() const;
  inline void set_rolename(const ::std::string& value);
  inline void set_rolename(const char* value);
  inline void set_rolename(const char* value, size_t size);
  inline ::std::string* mutable_rolename();
  inline ::std::string* release_rolename();
  inline void set_allocated_rolename(::std::string* rolename);

  // required int32 vipLvl = 3;
  inline bool has_viplvl() const;
  inline void clear_viplvl();
  static const int kVipLvlFieldNumber = 3;
  inline ::google::protobuf::int32 viplvl() const;
  inline void set_viplvl(::google::protobuf::int32 value);

  // required int32 coin = 4;
  inline bool has_coin() const;
  inline void clear_coin();
  static const int kCoinFieldNumber = 4;
  inline ::google::protobuf::int32 coin() const;
  inline void set_coin(::google::protobuf::int32 value);

  // required int32 rmb = 5;
  inline bool has_rmb() const;
  inline void clear_rmb();
  static const int kRmbFieldNumber = 5;
  inline ::google::protobuf::int32 rmb() const;
  inline void set_rmb(::google::protobuf::int32 value);

  // required int32 stamina = 6;
  inline bool has_stamina() const;
  inline void clear_stamina();
  static const int kStaminaFieldNumber = 6;
  inline ::google::protobuf::int32 stamina() const;
  inline void set_stamina(::google::protobuf::int32 value);

  // required int32 leftHpItemNum = 7;
  inline bool has_lefthpitemnum() const;
  inline void clear_lefthpitemnum();
  static const int kLeftHpItemNumFieldNumber = 7;
  inline ::google::protobuf::int32 lefthpitemnum() const;
  inline void set_lefthpitemnum(::google::protobuf::int32 value);

  // required int32 curHp = 8;
  inline bool has_curhp() const;
  inline void clear_curhp();
  static const int kCurHpFieldNumber = 8;
  inline ::google::protobuf::int32 curhp() const;
  inline void set_curhp(::google::protobuf::int32 value);

  // required int32 ranking = 9;
  inline bool has_ranking() const;
  inline void clear_ranking();
  static const int kRankingFieldNumber = 9;
  inline ::google::protobuf::int32 ranking() const;
  inline void set_ranking(::google::protobuf::int32 value);

  // required int32 curLibId = 10;
  inline bool has_curlibid() const;
  inline void clear_curlibid();
  static const int kCurLibIdFieldNumber = 10;
  inline ::google::protobuf::int32 curlibid() const;
  inline void set_curlibid(::google::protobuf::int32 value);

  // required int64 userId = 11;
  inline bool has_userid() const;
  inline void clear_userid();
  static const int kUserIdFieldNumber = 11;
  inline ::google::protobuf::int64 userid() const;
  inline void set_userid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:PRole)
 private:
  inline void set_has_roleid();
  inline void clear_has_roleid();
  inline void set_has_rolename();
  inline void clear_has_rolename();
  inline void set_has_viplvl();
  inline void clear_has_viplvl();
  inline void set_has_coin();
  inline void clear_has_coin();
  inline void set_has_rmb();
  inline void clear_has_rmb();
  inline void set_has_stamina();
  inline void clear_has_stamina();
  inline void set_has_lefthpitemnum();
  inline void clear_has_lefthpitemnum();
  inline void set_has_curhp();
  inline void clear_has_curhp();
  inline void set_has_ranking();
  inline void clear_has_ranking();
  inline void set_has_curlibid();
  inline void clear_has_curlibid();
  inline void set_has_userid();
  inline void clear_has_userid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int64 roleid_;
  ::std::string* rolename_;
  ::google::protobuf::int32 viplvl_;
  ::google::protobuf::int32 coin_;
  ::google::protobuf::int32 rmb_;
  ::google::protobuf::int32 stamina_;
  ::google::protobuf::int32 lefthpitemnum_;
  ::google::protobuf::int32 curhp_;
  ::google::protobuf::int32 ranking_;
  ::google::protobuf::int32 curlibid_;
  ::google::protobuf::int64 userid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(11 + 31) / 32];

  friend void  protobuf_AddDesc_account_2eproto();
  friend void protobuf_AssignDesc_account_2eproto();
  friend void protobuf_ShutdownFile_account_2eproto();

  void InitAsDefaultInstance();
  static PRole* default_instance_;
};
// -------------------------------------------------------------------

class PUpRole : public ::google::protobuf::Message {
 public:
  PUpRole();
  virtual ~PUpRole();

  PUpRole(const PUpRole& from);

  inline PUpRole& operator=(const PUpRole& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PUpRole& default_instance();

  void Swap(PUpRole* other);

  // implements Message ----------------------------------------------

  PUpRole* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PUpRole& from);
  void MergeFrom(const PUpRole& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 fieldType = 1;
  inline bool has_fieldtype() const;
  inline void clear_fieldtype();
  static const int kFieldTypeFieldNumber = 1;
  inline ::google::protobuf::int32 fieldtype() const;
  inline void set_fieldtype(::google::protobuf::int32 value);

  // required int32 addValue = 2;
  inline bool has_addvalue() const;
  inline void clear_addvalue();
  static const int kAddValueFieldNumber = 2;
  inline ::google::protobuf::int32 addvalue() const;
  inline void set_addvalue(::google::protobuf::int32 value);

  // required int32 finalValue = 3;
  inline bool has_finalvalue() const;
  inline void clear_finalvalue();
  static const int kFinalValueFieldNumber = 3;
  inline ::google::protobuf::int32 finalvalue() const;
  inline void set_finalvalue(::google::protobuf::int32 value);

  // required string itemType = 4;
  inline bool has_itemtype() const;
  inline void clear_itemtype();
  static const int kItemTypeFieldNumber = 4;
  inline const ::std::string& itemtype() const;
  inline void set_itemtype(const ::std::string& value);
  inline void set_itemtype(const char* value);
  inline void set_itemtype(const char* value, size_t size);
  inline ::std::string* mutable_itemtype();
  inline ::std::string* release_itemtype();
  inline void set_allocated_itemtype(::std::string* itemtype);

  // required int64 updatePkId = 5;
  inline bool has_updatepkid() const;
  inline void clear_updatepkid();
  static const int kUpdatePkIdFieldNumber = 5;
  inline ::google::protobuf::int64 updatepkid() const;
  inline void set_updatepkid(::google::protobuf::int64 value);

  // optional string param = 6;
  inline bool has_param() const;
  inline void clear_param();
  static const int kParamFieldNumber = 6;
  inline const ::std::string& param() const;
  inline void set_param(const ::std::string& value);
  inline void set_param(const char* value);
  inline void set_param(const char* value, size_t size);
  inline ::std::string* mutable_param();
  inline ::std::string* release_param();
  inline void set_allocated_param(::std::string* param);

  // @@protoc_insertion_point(class_scope:PUpRole)
 private:
  inline void set_has_fieldtype();
  inline void clear_has_fieldtype();
  inline void set_has_addvalue();
  inline void clear_has_addvalue();
  inline void set_has_finalvalue();
  inline void clear_has_finalvalue();
  inline void set_has_itemtype();
  inline void clear_has_itemtype();
  inline void set_has_updatepkid();
  inline void clear_has_updatepkid();
  inline void set_has_param();
  inline void clear_has_param();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 fieldtype_;
  ::google::protobuf::int32 addvalue_;
  ::std::string* itemtype_;
  ::google::protobuf::int64 updatepkid_;
  ::std::string* param_;
  ::google::protobuf::int32 finalvalue_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_account_2eproto();
  friend void protobuf_AssignDesc_account_2eproto();
  friend void protobuf_ShutdownFile_account_2eproto();

  void InitAsDefaultInstance();
  static PUpRole* default_instance_;
};
// ===================================================================


// ===================================================================

// LoginReq

// required string account = 1;
inline bool LoginReq::has_account() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginReq::set_has_account() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginReq::clear_has_account() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginReq::clear_account() {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    account_->clear();
  }
  clear_has_account();
}
inline const ::std::string& LoginReq::account() const {
  return *account_;
}
inline void LoginReq::set_account(const ::std::string& value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void LoginReq::set_account(const char* value) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(value);
}
inline void LoginReq::set_account(const char* value, size_t size) {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  account_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LoginReq::mutable_account() {
  set_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    account_ = new ::std::string;
  }
  return account_;
}
inline ::std::string* LoginReq::release_account() {
  clear_has_account();
  if (account_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = account_;
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LoginReq::set_allocated_account(::std::string* account) {
  if (account_ != &::google::protobuf::internal::kEmptyString) {
    delete account_;
  }
  if (account) {
    set_has_account();
    account_ = account;
  } else {
    clear_has_account();
    account_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string key = 2;
inline bool LoginReq::has_key() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginReq::set_has_key() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginReq::clear_has_key() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginReq::clear_key() {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    key_->clear();
  }
  clear_has_key();
}
inline const ::std::string& LoginReq::key() const {
  return *key_;
}
inline void LoginReq::set_key(const ::std::string& value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void LoginReq::set_key(const char* value) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(value);
}
inline void LoginReq::set_key(const char* value, size_t size) {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  key_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* LoginReq::mutable_key() {
  set_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    key_ = new ::std::string;
  }
  return key_;
}
inline ::std::string* LoginReq::release_key() {
  clear_has_key();
  if (key_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = key_;
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void LoginReq::set_allocated_key(::std::string* key) {
  if (key_ != &::google::protobuf::internal::kEmptyString) {
    delete key_;
  }
  if (key) {
    set_has_key();
    key_ = key;
  } else {
    clear_has_key();
    key_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 areaId = 3;
inline bool LoginReq::has_areaid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LoginReq::set_has_areaid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LoginReq::clear_has_areaid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LoginReq::clear_areaid() {
  areaid_ = 0;
  clear_has_areaid();
}
inline ::google::protobuf::int32 LoginReq::areaid() const {
  return areaid_;
}
inline void LoginReq::set_areaid(::google::protobuf::int32 value) {
  set_has_areaid();
  areaid_ = value;
}

// -------------------------------------------------------------------

// LoginResp

// required int32 result = 1;
inline bool LoginResp::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginResp::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginResp::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginResp::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 LoginResp::result() const {
  return result_;
}
inline void LoginResp::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}

// optional .PRole role = 2;
inline bool LoginResp::has_role() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LoginResp::set_has_role() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LoginResp::clear_has_role() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LoginResp::clear_role() {
  if (role_ != NULL) role_->::PRole::Clear();
  clear_has_role();
}
inline const ::PRole& LoginResp::role() const {
  return role_ != NULL ? *role_ : *default_instance_->role_;
}
inline ::PRole* LoginResp::mutable_role() {
  set_has_role();
  if (role_ == NULL) role_ = new ::PRole;
  return role_;
}
inline ::PRole* LoginResp::release_role() {
  clear_has_role();
  ::PRole* temp = role_;
  role_ = NULL;
  return temp;
}
inline void LoginResp::set_allocated_role(::PRole* role) {
  delete role_;
  role_ = role;
  if (role) {
    set_has_role();
  } else {
    clear_has_role();
  }
}

// -------------------------------------------------------------------

// CreateRoleReq

// required int32 spriteId = 1;
inline bool CreateRoleReq::has_spriteid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateRoleReq::set_has_spriteid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateRoleReq::clear_has_spriteid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateRoleReq::clear_spriteid() {
  spriteid_ = 0;
  clear_has_spriteid();
}
inline ::google::protobuf::int32 CreateRoleReq::spriteid() const {
  return spriteid_;
}
inline void CreateRoleReq::set_spriteid(::google::protobuf::int32 value) {
  set_has_spriteid();
  spriteid_ = value;
}

// required string roleName = 2;
inline bool CreateRoleReq::has_rolename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateRoleReq::set_has_rolename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateRoleReq::clear_has_rolename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateRoleReq::clear_rolename() {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    rolename_->clear();
  }
  clear_has_rolename();
}
inline const ::std::string& CreateRoleReq::rolename() const {
  return *rolename_;
}
inline void CreateRoleReq::set_rolename(const ::std::string& value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void CreateRoleReq::set_rolename(const char* value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void CreateRoleReq::set_rolename(const char* value, size_t size) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CreateRoleReq::mutable_rolename() {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  return rolename_;
}
inline ::std::string* CreateRoleReq::release_rolename() {
  clear_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rolename_;
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void CreateRoleReq::set_allocated_rolename(::std::string* rolename) {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    delete rolename_;
  }
  if (rolename) {
    set_has_rolename();
    rolename_ = rolename;
  } else {
    clear_has_rolename();
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// PRole

// required int64 roleId = 1;
inline bool PRole::has_roleid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PRole::set_has_roleid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PRole::clear_has_roleid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PRole::clear_roleid() {
  roleid_ = GOOGLE_LONGLONG(0);
  clear_has_roleid();
}
inline ::google::protobuf::int64 PRole::roleid() const {
  return roleid_;
}
inline void PRole::set_roleid(::google::protobuf::int64 value) {
  set_has_roleid();
  roleid_ = value;
}

// required string roleName = 2;
inline bool PRole::has_rolename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PRole::set_has_rolename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PRole::clear_has_rolename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PRole::clear_rolename() {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    rolename_->clear();
  }
  clear_has_rolename();
}
inline const ::std::string& PRole::rolename() const {
  return *rolename_;
}
inline void PRole::set_rolename(const ::std::string& value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void PRole::set_rolename(const char* value) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(value);
}
inline void PRole::set_rolename(const char* value, size_t size) {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  rolename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PRole::mutable_rolename() {
  set_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    rolename_ = new ::std::string;
  }
  return rolename_;
}
inline ::std::string* PRole::release_rolename() {
  clear_has_rolename();
  if (rolename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rolename_;
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PRole::set_allocated_rolename(::std::string* rolename) {
  if (rolename_ != &::google::protobuf::internal::kEmptyString) {
    delete rolename_;
  }
  if (rolename) {
    set_has_rolename();
    rolename_ = rolename;
  } else {
    clear_has_rolename();
    rolename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int32 vipLvl = 3;
inline bool PRole::has_viplvl() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PRole::set_has_viplvl() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PRole::clear_has_viplvl() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PRole::clear_viplvl() {
  viplvl_ = 0;
  clear_has_viplvl();
}
inline ::google::protobuf::int32 PRole::viplvl() const {
  return viplvl_;
}
inline void PRole::set_viplvl(::google::protobuf::int32 value) {
  set_has_viplvl();
  viplvl_ = value;
}

// required int32 coin = 4;
inline bool PRole::has_coin() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PRole::set_has_coin() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PRole::clear_has_coin() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PRole::clear_coin() {
  coin_ = 0;
  clear_has_coin();
}
inline ::google::protobuf::int32 PRole::coin() const {
  return coin_;
}
inline void PRole::set_coin(::google::protobuf::int32 value) {
  set_has_coin();
  coin_ = value;
}

// required int32 rmb = 5;
inline bool PRole::has_rmb() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PRole::set_has_rmb() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PRole::clear_has_rmb() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PRole::clear_rmb() {
  rmb_ = 0;
  clear_has_rmb();
}
inline ::google::protobuf::int32 PRole::rmb() const {
  return rmb_;
}
inline void PRole::set_rmb(::google::protobuf::int32 value) {
  set_has_rmb();
  rmb_ = value;
}

// required int32 stamina = 6;
inline bool PRole::has_stamina() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PRole::set_has_stamina() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PRole::clear_has_stamina() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PRole::clear_stamina() {
  stamina_ = 0;
  clear_has_stamina();
}
inline ::google::protobuf::int32 PRole::stamina() const {
  return stamina_;
}
inline void PRole::set_stamina(::google::protobuf::int32 value) {
  set_has_stamina();
  stamina_ = value;
}

// required int32 leftHpItemNum = 7;
inline bool PRole::has_lefthpitemnum() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PRole::set_has_lefthpitemnum() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PRole::clear_has_lefthpitemnum() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PRole::clear_lefthpitemnum() {
  lefthpitemnum_ = 0;
  clear_has_lefthpitemnum();
}
inline ::google::protobuf::int32 PRole::lefthpitemnum() const {
  return lefthpitemnum_;
}
inline void PRole::set_lefthpitemnum(::google::protobuf::int32 value) {
  set_has_lefthpitemnum();
  lefthpitemnum_ = value;
}

// required int32 curHp = 8;
inline bool PRole::has_curhp() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PRole::set_has_curhp() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PRole::clear_has_curhp() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PRole::clear_curhp() {
  curhp_ = 0;
  clear_has_curhp();
}
inline ::google::protobuf::int32 PRole::curhp() const {
  return curhp_;
}
inline void PRole::set_curhp(::google::protobuf::int32 value) {
  set_has_curhp();
  curhp_ = value;
}

// required int32 ranking = 9;
inline bool PRole::has_ranking() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PRole::set_has_ranking() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PRole::clear_has_ranking() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PRole::clear_ranking() {
  ranking_ = 0;
  clear_has_ranking();
}
inline ::google::protobuf::int32 PRole::ranking() const {
  return ranking_;
}
inline void PRole::set_ranking(::google::protobuf::int32 value) {
  set_has_ranking();
  ranking_ = value;
}

// required int32 curLibId = 10;
inline bool PRole::has_curlibid() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void PRole::set_has_curlibid() {
  _has_bits_[0] |= 0x00000200u;
}
inline void PRole::clear_has_curlibid() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void PRole::clear_curlibid() {
  curlibid_ = 0;
  clear_has_curlibid();
}
inline ::google::protobuf::int32 PRole::curlibid() const {
  return curlibid_;
}
inline void PRole::set_curlibid(::google::protobuf::int32 value) {
  set_has_curlibid();
  curlibid_ = value;
}

// required int64 userId = 11;
inline bool PRole::has_userid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PRole::set_has_userid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PRole::clear_has_userid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PRole::clear_userid() {
  userid_ = GOOGLE_LONGLONG(0);
  clear_has_userid();
}
inline ::google::protobuf::int64 PRole::userid() const {
  return userid_;
}
inline void PRole::set_userid(::google::protobuf::int64 value) {
  set_has_userid();
  userid_ = value;
}

// -------------------------------------------------------------------

// PUpRole

// required int32 fieldType = 1;
inline bool PUpRole::has_fieldtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PUpRole::set_has_fieldtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PUpRole::clear_has_fieldtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PUpRole::clear_fieldtype() {
  fieldtype_ = 0;
  clear_has_fieldtype();
}
inline ::google::protobuf::int32 PUpRole::fieldtype() const {
  return fieldtype_;
}
inline void PUpRole::set_fieldtype(::google::protobuf::int32 value) {
  set_has_fieldtype();
  fieldtype_ = value;
}

// required int32 addValue = 2;
inline bool PUpRole::has_addvalue() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PUpRole::set_has_addvalue() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PUpRole::clear_has_addvalue() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PUpRole::clear_addvalue() {
  addvalue_ = 0;
  clear_has_addvalue();
}
inline ::google::protobuf::int32 PUpRole::addvalue() const {
  return addvalue_;
}
inline void PUpRole::set_addvalue(::google::protobuf::int32 value) {
  set_has_addvalue();
  addvalue_ = value;
}

// required int32 finalValue = 3;
inline bool PUpRole::has_finalvalue() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PUpRole::set_has_finalvalue() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PUpRole::clear_has_finalvalue() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PUpRole::clear_finalvalue() {
  finalvalue_ = 0;
  clear_has_finalvalue();
}
inline ::google::protobuf::int32 PUpRole::finalvalue() const {
  return finalvalue_;
}
inline void PUpRole::set_finalvalue(::google::protobuf::int32 value) {
  set_has_finalvalue();
  finalvalue_ = value;
}

// required string itemType = 4;
inline bool PUpRole::has_itemtype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PUpRole::set_has_itemtype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PUpRole::clear_has_itemtype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PUpRole::clear_itemtype() {
  if (itemtype_ != &::google::protobuf::internal::kEmptyString) {
    itemtype_->clear();
  }
  clear_has_itemtype();
}
inline const ::std::string& PUpRole::itemtype() const {
  return *itemtype_;
}
inline void PUpRole::set_itemtype(const ::std::string& value) {
  set_has_itemtype();
  if (itemtype_ == &::google::protobuf::internal::kEmptyString) {
    itemtype_ = new ::std::string;
  }
  itemtype_->assign(value);
}
inline void PUpRole::set_itemtype(const char* value) {
  set_has_itemtype();
  if (itemtype_ == &::google::protobuf::internal::kEmptyString) {
    itemtype_ = new ::std::string;
  }
  itemtype_->assign(value);
}
inline void PUpRole::set_itemtype(const char* value, size_t size) {
  set_has_itemtype();
  if (itemtype_ == &::google::protobuf::internal::kEmptyString) {
    itemtype_ = new ::std::string;
  }
  itemtype_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PUpRole::mutable_itemtype() {
  set_has_itemtype();
  if (itemtype_ == &::google::protobuf::internal::kEmptyString) {
    itemtype_ = new ::std::string;
  }
  return itemtype_;
}
inline ::std::string* PUpRole::release_itemtype() {
  clear_has_itemtype();
  if (itemtype_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = itemtype_;
    itemtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PUpRole::set_allocated_itemtype(::std::string* itemtype) {
  if (itemtype_ != &::google::protobuf::internal::kEmptyString) {
    delete itemtype_;
  }
  if (itemtype) {
    set_has_itemtype();
    itemtype_ = itemtype;
  } else {
    clear_has_itemtype();
    itemtype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required int64 updatePkId = 5;
inline bool PUpRole::has_updatepkid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PUpRole::set_has_updatepkid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PUpRole::clear_has_updatepkid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PUpRole::clear_updatepkid() {
  updatepkid_ = GOOGLE_LONGLONG(0);
  clear_has_updatepkid();
}
inline ::google::protobuf::int64 PUpRole::updatepkid() const {
  return updatepkid_;
}
inline void PUpRole::set_updatepkid(::google::protobuf::int64 value) {
  set_has_updatepkid();
  updatepkid_ = value;
}

// optional string param = 6;
inline bool PUpRole::has_param() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PUpRole::set_has_param() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PUpRole::clear_has_param() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PUpRole::clear_param() {
  if (param_ != &::google::protobuf::internal::kEmptyString) {
    param_->clear();
  }
  clear_has_param();
}
inline const ::std::string& PUpRole::param() const {
  return *param_;
}
inline void PUpRole::set_param(const ::std::string& value) {
  set_has_param();
  if (param_ == &::google::protobuf::internal::kEmptyString) {
    param_ = new ::std::string;
  }
  param_->assign(value);
}
inline void PUpRole::set_param(const char* value) {
  set_has_param();
  if (param_ == &::google::protobuf::internal::kEmptyString) {
    param_ = new ::std::string;
  }
  param_->assign(value);
}
inline void PUpRole::set_param(const char* value, size_t size) {
  set_has_param();
  if (param_ == &::google::protobuf::internal::kEmptyString) {
    param_ = new ::std::string;
  }
  param_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PUpRole::mutable_param() {
  set_has_param();
  if (param_ == &::google::protobuf::internal::kEmptyString) {
    param_ = new ::std::string;
  }
  return param_;
}
inline ::std::string* PUpRole::release_param() {
  clear_has_param();
  if (param_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = param_;
    param_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PUpRole::set_allocated_param(::std::string* param) {
  if (param_ != &::google::protobuf::internal::kEmptyString) {
    delete param_;
  }
  if (param) {
    set_has_param();
    param_ = param;
  } else {
    clear_has_param();
    param_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_account_2eproto__INCLUDED
