// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

#ifndef PROTOBUF_battle_2eproto__INCLUDED
#define PROTOBUF_battle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_battle_2eproto();
void protobuf_AssignDesc_battle_2eproto();
void protobuf_ShutdownFile_battle_2eproto();

class PBattle;
class PFightItem;
class PRound;
class Phurt;
class PTarget;

// ===================================================================

class PBattle : public ::google::protobuf::Message {
 public:
  PBattle();
  virtual ~PBattle();

  PBattle(const PBattle& from);

  inline PBattle& operator=(const PBattle& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PBattle& default_instance();

  void Swap(PBattle* other);

  // implements Message ----------------------------------------------

  PBattle* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PBattle& from);
  void MergeFrom(const PBattle& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PFightItem heros = 1;
  inline int heros_size() const;
  inline void clear_heros();
  static const int kHerosFieldNumber = 1;
  inline const ::PFightItem& heros(int index) const;
  inline ::PFightItem* mutable_heros(int index);
  inline ::PFightItem* add_heros();
  inline const ::google::protobuf::RepeatedPtrField< ::PFightItem >&
      heros() const;
  inline ::google::protobuf::RepeatedPtrField< ::PFightItem >*
      mutable_heros();

  // repeated .PRound rounds = 2;
  inline int rounds_size() const;
  inline void clear_rounds();
  static const int kRoundsFieldNumber = 2;
  inline const ::PRound& rounds(int index) const;
  inline ::PRound* mutable_rounds(int index);
  inline ::PRound* add_rounds();
  inline const ::google::protobuf::RepeatedPtrField< ::PRound >&
      rounds() const;
  inline ::google::protobuf::RepeatedPtrField< ::PRound >*
      mutable_rounds();

  // repeated int32 cards = 3;
  inline int cards_size() const;
  inline void clear_cards();
  static const int kCardsFieldNumber = 3;
  inline ::google::protobuf::int32 cards(int index) const;
  inline void set_cards(int index, ::google::protobuf::int32 value);
  inline void add_cards(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cards() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cards();

  // required int32 gold = 4;
  inline bool has_gold() const;
  inline void clear_gold();
  static const int kGoldFieldNumber = 4;
  inline ::google::protobuf::int32 gold() const;
  inline void set_gold(::google::protobuf::int32 value);

  // required int32 exp = 5;
  inline bool has_exp() const;
  inline void clear_exp();
  static const int kExpFieldNumber = 5;
  inline ::google::protobuf::int32 exp() const;
  inline void set_exp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PBattle)
 private:
  inline void set_has_gold();
  inline void clear_has_gold();
  inline void set_has_exp();
  inline void clear_has_exp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::PFightItem > heros_;
  ::google::protobuf::RepeatedPtrField< ::PRound > rounds_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cards_;
  ::google::protobuf::int32 gold_;
  ::google::protobuf::int32 exp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PBattle* default_instance_;
};
// -------------------------------------------------------------------

class PFightItem : public ::google::protobuf::Message {
 public:
  PFightItem();
  virtual ~PFightItem();

  PFightItem(const PFightItem& from);

  inline PFightItem& operator=(const PFightItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PFightItem& default_instance();

  void Swap(PFightItem* other);

  // implements Message ----------------------------------------------

  PFightItem* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PFightItem& from);
  void MergeFrom(const PFightItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required int32 hp = 2;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 2;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // required string name = 3;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 3;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required string icon = 4;
  inline bool has_icon() const;
  inline void clear_icon();
  static const int kIconFieldNumber = 4;
  inline const ::std::string& icon() const;
  inline void set_icon(const ::std::string& value);
  inline void set_icon(const char* value);
  inline void set_icon(const char* value, size_t size);
  inline ::std::string* mutable_icon();
  inline ::std::string* release_icon();
  inline void set_allocated_icon(::std::string* icon);

  // required string avatar = 5;
  inline bool has_avatar() const;
  inline void clear_avatar();
  static const int kAvatarFieldNumber = 5;
  inline const ::std::string& avatar() const;
  inline void set_avatar(const ::std::string& value);
  inline void set_avatar(const char* value);
  inline void set_avatar(const char* value, size_t size);
  inline ::std::string* mutable_avatar();
  inline ::std::string* release_avatar();
  inline void set_allocated_avatar(::std::string* avatar);

  // required string friendID = 6;
  inline bool has_friendid() const;
  inline void clear_friendid();
  static const int kFriendIDFieldNumber = 6;
  inline const ::std::string& friendid() const;
  inline void set_friendid(const ::std::string& value);
  inline void set_friendid(const char* value);
  inline void set_friendid(const char* value, size_t size);
  inline ::std::string* mutable_friendid();
  inline ::std::string* release_friendid();
  inline void set_allocated_friendid(::std::string* friendid);

  // required string friendName = 7;
  inline bool has_friendname() const;
  inline void clear_friendname();
  static const int kFriendNameFieldNumber = 7;
  inline const ::std::string& friendname() const;
  inline void set_friendname(const ::std::string& value);
  inline void set_friendname(const char* value);
  inline void set_friendname(const char* value, size_t size);
  inline ::std::string* mutable_friendname();
  inline ::std::string* release_friendname();
  inline void set_allocated_friendname(::std::string* friendname);

  // required string friendIcon = 8;
  inline bool has_friendicon() const;
  inline void clear_friendicon();
  static const int kFriendIconFieldNumber = 8;
  inline const ::std::string& friendicon() const;
  inline void set_friendicon(const ::std::string& value);
  inline void set_friendicon(const char* value);
  inline void set_friendicon(const char* value, size_t size);
  inline ::std::string* mutable_friendicon();
  inline ::std::string* release_friendicon();
  inline void set_allocated_friendicon(::std::string* friendicon);

  // required string friendAvatar = 9;
  inline bool has_friendavatar() const;
  inline void clear_friendavatar();
  static const int kFriendAvatarFieldNumber = 9;
  inline const ::std::string& friendavatar() const;
  inline void set_friendavatar(const ::std::string& value);
  inline void set_friendavatar(const char* value);
  inline void set_friendavatar(const char* value, size_t size);
  inline ::std::string* mutable_friendavatar();
  inline ::std::string* release_friendavatar();
  inline void set_allocated_friendavatar(::std::string* friendavatar);

  // @@protoc_insertion_point(class_scope:PFightItem)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_icon();
  inline void clear_has_icon();
  inline void set_has_avatar();
  inline void clear_has_avatar();
  inline void set_has_friendid();
  inline void clear_has_friendid();
  inline void set_has_friendname();
  inline void clear_has_friendname();
  inline void set_has_friendicon();
  inline void clear_has_friendicon();
  inline void set_has_friendavatar();
  inline void clear_has_friendavatar();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 hp_;
  ::std::string* name_;
  ::std::string* icon_;
  ::std::string* avatar_;
  ::std::string* friendid_;
  ::std::string* friendname_;
  ::std::string* friendicon_;
  ::std::string* friendavatar_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PFightItem* default_instance_;
};
// -------------------------------------------------------------------

class PRound : public ::google::protobuf::Message {
 public:
  PRound();
  virtual ~PRound();

  PRound(const PRound& from);

  inline PRound& operator=(const PRound& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PRound& default_instance();

  void Swap(PRound* other);

  // implements Message ----------------------------------------------

  PRound* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PRound& from);
  void MergeFrom(const PRound& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 source = 1;
  inline bool has_source() const;
  inline void clear_source();
  static const int kSourceFieldNumber = 1;
  inline ::google::protobuf::int32 source() const;
  inline void set_source(::google::protobuf::int32 value);

  // required bool isSkip = 2;
  inline bool has_isskip() const;
  inline void clear_isskip();
  static const int kIsSkipFieldNumber = 2;
  inline bool isskip() const;
  inline void set_isskip(bool value);

  // optional int32 target = 3;
  inline bool has_target() const;
  inline void clear_target();
  static const int kTargetFieldNumber = 3;
  inline ::google::protobuf::int32 target() const;
  inline void set_target(::google::protobuf::int32 value);

  // repeated .Phurt cards = 4;
  inline int cards_size() const;
  inline void clear_cards();
  static const int kCardsFieldNumber = 4;
  inline const ::Phurt& cards(int index) const;
  inline ::Phurt* mutable_cards(int index);
  inline ::Phurt* add_cards();
  inline const ::google::protobuf::RepeatedPtrField< ::Phurt >&
      cards() const;
  inline ::google::protobuf::RepeatedPtrField< ::Phurt >*
      mutable_cards();

  // optional int32 aoyiSkillID = 5;
  inline bool has_aoyiskillid() const;
  inline void clear_aoyiskillid();
  static const int kAoyiSkillIDFieldNumber = 5;
  inline ::google::protobuf::int32 aoyiskillid() const;
  inline void set_aoyiskillid(::google::protobuf::int32 value);

  // repeated string delIcons = 6;
  inline int delicons_size() const;
  inline void clear_delicons();
  static const int kDelIconsFieldNumber = 6;
  inline const ::std::string& delicons(int index) const;
  inline ::std::string* mutable_delicons(int index);
  inline void set_delicons(int index, const ::std::string& value);
  inline void set_delicons(int index, const char* value);
  inline void set_delicons(int index, const char* value, size_t size);
  inline ::std::string* add_delicons();
  inline void add_delicons(const ::std::string& value);
  inline void add_delicons(const char* value);
  inline void add_delicons(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& delicons() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_delicons();

  // repeated int32 delStates = 7;
  inline int delstates_size() const;
  inline void clear_delstates();
  static const int kDelStatesFieldNumber = 7;
  inline ::google::protobuf::int32 delstates(int index) const;
  inline void set_delstates(int index, ::google::protobuf::int32 value);
  inline void add_delstates(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      delstates() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_delstates();

  // repeated int32 buffHps = 8;
  inline int buffhps_size() const;
  inline void clear_buffhps();
  static const int kBuffHpsFieldNumber = 8;
  inline ::google::protobuf::int32 buffhps(int index) const;
  inline void set_buffhps(int index, ::google::protobuf::int32 value);
  inline void add_buffhps(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      buffhps() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_buffhps();

  // required int32 leftHp = 9;
  inline bool has_lefthp() const;
  inline void clear_lefthp();
  static const int kLeftHpFieldNumber = 9;
  inline ::google::protobuf::int32 lefthp() const;
  inline void set_lefthp(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PRound)
 private:
  inline void set_has_source();
  inline void clear_has_source();
  inline void set_has_isskip();
  inline void clear_has_isskip();
  inline void set_has_target();
  inline void clear_has_target();
  inline void set_has_aoyiskillid();
  inline void clear_has_aoyiskillid();
  inline void set_has_lefthp();
  inline void clear_has_lefthp();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 source_;
  bool isskip_;
  ::google::protobuf::RepeatedPtrField< ::Phurt > cards_;
  ::google::protobuf::int32 target_;
  ::google::protobuf::int32 aoyiskillid_;
  ::google::protobuf::RepeatedPtrField< ::std::string> delicons_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > delstates_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > buffhps_;
  ::google::protobuf::int32 lefthp_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(9 + 31) / 32];

  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PRound* default_instance_;
};
// -------------------------------------------------------------------

class Phurt : public ::google::protobuf::Message {
 public:
  Phurt();
  virtual ~Phurt();

  Phurt(const Phurt& from);

  inline Phurt& operator=(const Phurt& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Phurt& default_instance();

  void Swap(Phurt* other);

  // implements Message ----------------------------------------------

  Phurt* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Phurt& from);
  void MergeFrom(const Phurt& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 card = 1;
  inline bool has_card() const;
  inline void clear_card();
  static const int kCardFieldNumber = 1;
  inline ::google::protobuf::int32 card() const;
  inline void set_card(::google::protobuf::int32 value);

  // required bool skillID = 2;
  inline bool has_skillid() const;
  inline void clear_skillid();
  static const int kSkillIDFieldNumber = 2;
  inline bool skillid() const;
  inline void set_skillid(bool value);

  // repeated .PTarget targets = 3;
  inline int targets_size() const;
  inline void clear_targets();
  static const int kTargetsFieldNumber = 3;
  inline const ::PTarget& targets(int index) const;
  inline ::PTarget* mutable_targets(int index);
  inline ::PTarget* add_targets();
  inline const ::google::protobuf::RepeatedPtrField< ::PTarget >&
      targets() const;
  inline ::google::protobuf::RepeatedPtrField< ::PTarget >*
      mutable_targets();

  // @@protoc_insertion_point(class_scope:Phurt)
 private:
  inline void set_has_card();
  inline void clear_has_card();
  inline void set_has_skillid();
  inline void clear_has_skillid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 card_;
  bool skillid_;
  ::google::protobuf::RepeatedPtrField< ::PTarget > targets_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static Phurt* default_instance_;
};
// -------------------------------------------------------------------

class PTarget : public ::google::protobuf::Message {
 public:
  PTarget();
  virtual ~PTarget();

  PTarget(const PTarget& from);

  inline PTarget& operator=(const PTarget& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PTarget& default_instance();

  void Swap(PTarget* other);

  // implements Message ----------------------------------------------

  PTarget* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PTarget& from);
  void MergeFrom(const PTarget& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 targetID = 1;
  inline bool has_targetid() const;
  inline void clear_targetid();
  static const int kTargetIDFieldNumber = 1;
  inline ::google::protobuf::int32 targetid() const;
  inline void set_targetid(::google::protobuf::int32 value);

  // repeated int32 state = 2;
  inline int state_size() const;
  inline void clear_state();
  static const int kStateFieldNumber = 2;
  inline ::google::protobuf::int32 state(int index) const;
  inline void set_state(int index, ::google::protobuf::int32 value);
  inline void add_state(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      state() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_state();

  // repeated string buffIcon = 3;
  inline int bufficon_size() const;
  inline void clear_bufficon();
  static const int kBuffIconFieldNumber = 3;
  inline const ::std::string& bufficon(int index) const;
  inline ::std::string* mutable_bufficon(int index);
  inline void set_bufficon(int index, const ::std::string& value);
  inline void set_bufficon(int index, const char* value);
  inline void set_bufficon(int index, const char* value, size_t size);
  inline ::std::string* add_bufficon();
  inline void add_bufficon(const ::std::string& value);
  inline void add_bufficon(const char* value);
  inline void add_bufficon(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& bufficon() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_bufficon();

  // required int32 hp = 4;
  inline bool has_hp() const;
  inline void clear_hp();
  static const int kHpFieldNumber = 4;
  inline ::google::protobuf::int32 hp() const;
  inline void set_hp(::google::protobuf::int32 value);

  // required int32 leftHp = 5;
  inline bool has_lefthp() const;
  inline void clear_lefthp();
  static const int kLeftHpFieldNumber = 5;
  inline ::google::protobuf::int32 lefthp() const;
  inline void set_lefthp(::google::protobuf::int32 value);

  // required int32 hpTypes = 6;
  inline bool has_hptypes() const;
  inline void clear_hptypes();
  static const int kHpTypesFieldNumber = 6;
  inline ::google::protobuf::int32 hptypes() const;
  inline void set_hptypes(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PTarget)
 private:
  inline void set_has_targetid();
  inline void clear_has_targetid();
  inline void set_has_hp();
  inline void clear_has_hp();
  inline void set_has_lefthp();
  inline void clear_has_lefthp();
  inline void set_has_hptypes();
  inline void clear_has_hptypes();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > state_;
  ::google::protobuf::int32 targetid_;
  ::google::protobuf::int32 hp_;
  ::google::protobuf::RepeatedPtrField< ::std::string> bufficon_;
  ::google::protobuf::int32 lefthp_;
  ::google::protobuf::int32 hptypes_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_battle_2eproto();
  friend void protobuf_AssignDesc_battle_2eproto();
  friend void protobuf_ShutdownFile_battle_2eproto();

  void InitAsDefaultInstance();
  static PTarget* default_instance_;
};
// ===================================================================


// ===================================================================

// PBattle

// repeated .PFightItem heros = 1;
inline int PBattle::heros_size() const {
  return heros_.size();
}
inline void PBattle::clear_heros() {
  heros_.Clear();
}
inline const ::PFightItem& PBattle::heros(int index) const {
  return heros_.Get(index);
}
inline ::PFightItem* PBattle::mutable_heros(int index) {
  return heros_.Mutable(index);
}
inline ::PFightItem* PBattle::add_heros() {
  return heros_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PFightItem >&
PBattle::heros() const {
  return heros_;
}
inline ::google::protobuf::RepeatedPtrField< ::PFightItem >*
PBattle::mutable_heros() {
  return &heros_;
}

// repeated .PRound rounds = 2;
inline int PBattle::rounds_size() const {
  return rounds_.size();
}
inline void PBattle::clear_rounds() {
  rounds_.Clear();
}
inline const ::PRound& PBattle::rounds(int index) const {
  return rounds_.Get(index);
}
inline ::PRound* PBattle::mutable_rounds(int index) {
  return rounds_.Mutable(index);
}
inline ::PRound* PBattle::add_rounds() {
  return rounds_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PRound >&
PBattle::rounds() const {
  return rounds_;
}
inline ::google::protobuf::RepeatedPtrField< ::PRound >*
PBattle::mutable_rounds() {
  return &rounds_;
}

// repeated int32 cards = 3;
inline int PBattle::cards_size() const {
  return cards_.size();
}
inline void PBattle::clear_cards() {
  cards_.Clear();
}
inline ::google::protobuf::int32 PBattle::cards(int index) const {
  return cards_.Get(index);
}
inline void PBattle::set_cards(int index, ::google::protobuf::int32 value) {
  cards_.Set(index, value);
}
inline void PBattle::add_cards(::google::protobuf::int32 value) {
  cards_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PBattle::cards() const {
  return cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PBattle::mutable_cards() {
  return &cards_;
}

// required int32 gold = 4;
inline bool PBattle::has_gold() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PBattle::set_has_gold() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PBattle::clear_has_gold() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PBattle::clear_gold() {
  gold_ = 0;
  clear_has_gold();
}
inline ::google::protobuf::int32 PBattle::gold() const {
  return gold_;
}
inline void PBattle::set_gold(::google::protobuf::int32 value) {
  set_has_gold();
  gold_ = value;
}

// required int32 exp = 5;
inline bool PBattle::has_exp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PBattle::set_has_exp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PBattle::clear_has_exp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PBattle::clear_exp() {
  exp_ = 0;
  clear_has_exp();
}
inline ::google::protobuf::int32 PBattle::exp() const {
  return exp_;
}
inline void PBattle::set_exp(::google::protobuf::int32 value) {
  set_has_exp();
  exp_ = value;
}

// -------------------------------------------------------------------

// PFightItem

// required int32 id = 1;
inline bool PFightItem::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PFightItem::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PFightItem::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PFightItem::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 PFightItem::id() const {
  return id_;
}
inline void PFightItem::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required int32 hp = 2;
inline bool PFightItem::has_hp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PFightItem::set_has_hp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PFightItem::clear_has_hp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PFightItem::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 PFightItem::hp() const {
  return hp_;
}
inline void PFightItem::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// required string name = 3;
inline bool PFightItem::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PFightItem::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PFightItem::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PFightItem::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& PFightItem::name() const {
  return *name_;
}
inline void PFightItem::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PFightItem::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void PFightItem::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* PFightItem::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string icon = 4;
inline bool PFightItem::has_icon() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PFightItem::set_has_icon() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PFightItem::clear_has_icon() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PFightItem::clear_icon() {
  if (icon_ != &::google::protobuf::internal::kEmptyString) {
    icon_->clear();
  }
  clear_has_icon();
}
inline const ::std::string& PFightItem::icon() const {
  return *icon_;
}
inline void PFightItem::set_icon(const ::std::string& value) {
  set_has_icon();
  if (icon_ == &::google::protobuf::internal::kEmptyString) {
    icon_ = new ::std::string;
  }
  icon_->assign(value);
}
inline void PFightItem::set_icon(const char* value) {
  set_has_icon();
  if (icon_ == &::google::protobuf::internal::kEmptyString) {
    icon_ = new ::std::string;
  }
  icon_->assign(value);
}
inline void PFightItem::set_icon(const char* value, size_t size) {
  set_has_icon();
  if (icon_ == &::google::protobuf::internal::kEmptyString) {
    icon_ = new ::std::string;
  }
  icon_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_icon() {
  set_has_icon();
  if (icon_ == &::google::protobuf::internal::kEmptyString) {
    icon_ = new ::std::string;
  }
  return icon_;
}
inline ::std::string* PFightItem::release_icon() {
  clear_has_icon();
  if (icon_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = icon_;
    icon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_icon(::std::string* icon) {
  if (icon_ != &::google::protobuf::internal::kEmptyString) {
    delete icon_;
  }
  if (icon) {
    set_has_icon();
    icon_ = icon;
  } else {
    clear_has_icon();
    icon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string avatar = 5;
inline bool PFightItem::has_avatar() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PFightItem::set_has_avatar() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PFightItem::clear_has_avatar() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PFightItem::clear_avatar() {
  if (avatar_ != &::google::protobuf::internal::kEmptyString) {
    avatar_->clear();
  }
  clear_has_avatar();
}
inline const ::std::string& PFightItem::avatar() const {
  return *avatar_;
}
inline void PFightItem::set_avatar(const ::std::string& value) {
  set_has_avatar();
  if (avatar_ == &::google::protobuf::internal::kEmptyString) {
    avatar_ = new ::std::string;
  }
  avatar_->assign(value);
}
inline void PFightItem::set_avatar(const char* value) {
  set_has_avatar();
  if (avatar_ == &::google::protobuf::internal::kEmptyString) {
    avatar_ = new ::std::string;
  }
  avatar_->assign(value);
}
inline void PFightItem::set_avatar(const char* value, size_t size) {
  set_has_avatar();
  if (avatar_ == &::google::protobuf::internal::kEmptyString) {
    avatar_ = new ::std::string;
  }
  avatar_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_avatar() {
  set_has_avatar();
  if (avatar_ == &::google::protobuf::internal::kEmptyString) {
    avatar_ = new ::std::string;
  }
  return avatar_;
}
inline ::std::string* PFightItem::release_avatar() {
  clear_has_avatar();
  if (avatar_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = avatar_;
    avatar_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_avatar(::std::string* avatar) {
  if (avatar_ != &::google::protobuf::internal::kEmptyString) {
    delete avatar_;
  }
  if (avatar) {
    set_has_avatar();
    avatar_ = avatar;
  } else {
    clear_has_avatar();
    avatar_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string friendID = 6;
inline bool PFightItem::has_friendid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PFightItem::set_has_friendid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PFightItem::clear_has_friendid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PFightItem::clear_friendid() {
  if (friendid_ != &::google::protobuf::internal::kEmptyString) {
    friendid_->clear();
  }
  clear_has_friendid();
}
inline const ::std::string& PFightItem::friendid() const {
  return *friendid_;
}
inline void PFightItem::set_friendid(const ::std::string& value) {
  set_has_friendid();
  if (friendid_ == &::google::protobuf::internal::kEmptyString) {
    friendid_ = new ::std::string;
  }
  friendid_->assign(value);
}
inline void PFightItem::set_friendid(const char* value) {
  set_has_friendid();
  if (friendid_ == &::google::protobuf::internal::kEmptyString) {
    friendid_ = new ::std::string;
  }
  friendid_->assign(value);
}
inline void PFightItem::set_friendid(const char* value, size_t size) {
  set_has_friendid();
  if (friendid_ == &::google::protobuf::internal::kEmptyString) {
    friendid_ = new ::std::string;
  }
  friendid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_friendid() {
  set_has_friendid();
  if (friendid_ == &::google::protobuf::internal::kEmptyString) {
    friendid_ = new ::std::string;
  }
  return friendid_;
}
inline ::std::string* PFightItem::release_friendid() {
  clear_has_friendid();
  if (friendid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = friendid_;
    friendid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_friendid(::std::string* friendid) {
  if (friendid_ != &::google::protobuf::internal::kEmptyString) {
    delete friendid_;
  }
  if (friendid) {
    set_has_friendid();
    friendid_ = friendid;
  } else {
    clear_has_friendid();
    friendid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string friendName = 7;
inline bool PFightItem::has_friendname() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PFightItem::set_has_friendname() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PFightItem::clear_has_friendname() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PFightItem::clear_friendname() {
  if (friendname_ != &::google::protobuf::internal::kEmptyString) {
    friendname_->clear();
  }
  clear_has_friendname();
}
inline const ::std::string& PFightItem::friendname() const {
  return *friendname_;
}
inline void PFightItem::set_friendname(const ::std::string& value) {
  set_has_friendname();
  if (friendname_ == &::google::protobuf::internal::kEmptyString) {
    friendname_ = new ::std::string;
  }
  friendname_->assign(value);
}
inline void PFightItem::set_friendname(const char* value) {
  set_has_friendname();
  if (friendname_ == &::google::protobuf::internal::kEmptyString) {
    friendname_ = new ::std::string;
  }
  friendname_->assign(value);
}
inline void PFightItem::set_friendname(const char* value, size_t size) {
  set_has_friendname();
  if (friendname_ == &::google::protobuf::internal::kEmptyString) {
    friendname_ = new ::std::string;
  }
  friendname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_friendname() {
  set_has_friendname();
  if (friendname_ == &::google::protobuf::internal::kEmptyString) {
    friendname_ = new ::std::string;
  }
  return friendname_;
}
inline ::std::string* PFightItem::release_friendname() {
  clear_has_friendname();
  if (friendname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = friendname_;
    friendname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_friendname(::std::string* friendname) {
  if (friendname_ != &::google::protobuf::internal::kEmptyString) {
    delete friendname_;
  }
  if (friendname) {
    set_has_friendname();
    friendname_ = friendname;
  } else {
    clear_has_friendname();
    friendname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string friendIcon = 8;
inline bool PFightItem::has_friendicon() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PFightItem::set_has_friendicon() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PFightItem::clear_has_friendicon() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PFightItem::clear_friendicon() {
  if (friendicon_ != &::google::protobuf::internal::kEmptyString) {
    friendicon_->clear();
  }
  clear_has_friendicon();
}
inline const ::std::string& PFightItem::friendicon() const {
  return *friendicon_;
}
inline void PFightItem::set_friendicon(const ::std::string& value) {
  set_has_friendicon();
  if (friendicon_ == &::google::protobuf::internal::kEmptyString) {
    friendicon_ = new ::std::string;
  }
  friendicon_->assign(value);
}
inline void PFightItem::set_friendicon(const char* value) {
  set_has_friendicon();
  if (friendicon_ == &::google::protobuf::internal::kEmptyString) {
    friendicon_ = new ::std::string;
  }
  friendicon_->assign(value);
}
inline void PFightItem::set_friendicon(const char* value, size_t size) {
  set_has_friendicon();
  if (friendicon_ == &::google::protobuf::internal::kEmptyString) {
    friendicon_ = new ::std::string;
  }
  friendicon_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_friendicon() {
  set_has_friendicon();
  if (friendicon_ == &::google::protobuf::internal::kEmptyString) {
    friendicon_ = new ::std::string;
  }
  return friendicon_;
}
inline ::std::string* PFightItem::release_friendicon() {
  clear_has_friendicon();
  if (friendicon_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = friendicon_;
    friendicon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_friendicon(::std::string* friendicon) {
  if (friendicon_ != &::google::protobuf::internal::kEmptyString) {
    delete friendicon_;
  }
  if (friendicon) {
    set_has_friendicon();
    friendicon_ = friendicon;
  } else {
    clear_has_friendicon();
    friendicon_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required string friendAvatar = 9;
inline bool PFightItem::has_friendavatar() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PFightItem::set_has_friendavatar() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PFightItem::clear_has_friendavatar() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PFightItem::clear_friendavatar() {
  if (friendavatar_ != &::google::protobuf::internal::kEmptyString) {
    friendavatar_->clear();
  }
  clear_has_friendavatar();
}
inline const ::std::string& PFightItem::friendavatar() const {
  return *friendavatar_;
}
inline void PFightItem::set_friendavatar(const ::std::string& value) {
  set_has_friendavatar();
  if (friendavatar_ == &::google::protobuf::internal::kEmptyString) {
    friendavatar_ = new ::std::string;
  }
  friendavatar_->assign(value);
}
inline void PFightItem::set_friendavatar(const char* value) {
  set_has_friendavatar();
  if (friendavatar_ == &::google::protobuf::internal::kEmptyString) {
    friendavatar_ = new ::std::string;
  }
  friendavatar_->assign(value);
}
inline void PFightItem::set_friendavatar(const char* value, size_t size) {
  set_has_friendavatar();
  if (friendavatar_ == &::google::protobuf::internal::kEmptyString) {
    friendavatar_ = new ::std::string;
  }
  friendavatar_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PFightItem::mutable_friendavatar() {
  set_has_friendavatar();
  if (friendavatar_ == &::google::protobuf::internal::kEmptyString) {
    friendavatar_ = new ::std::string;
  }
  return friendavatar_;
}
inline ::std::string* PFightItem::release_friendavatar() {
  clear_has_friendavatar();
  if (friendavatar_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = friendavatar_;
    friendavatar_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void PFightItem::set_allocated_friendavatar(::std::string* friendavatar) {
  if (friendavatar_ != &::google::protobuf::internal::kEmptyString) {
    delete friendavatar_;
  }
  if (friendavatar) {
    set_has_friendavatar();
    friendavatar_ = friendavatar;
  } else {
    clear_has_friendavatar();
    friendavatar_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// PRound

// required int32 source = 1;
inline bool PRound::has_source() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PRound::set_has_source() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PRound::clear_has_source() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PRound::clear_source() {
  source_ = 0;
  clear_has_source();
}
inline ::google::protobuf::int32 PRound::source() const {
  return source_;
}
inline void PRound::set_source(::google::protobuf::int32 value) {
  set_has_source();
  source_ = value;
}

// required bool isSkip = 2;
inline bool PRound::has_isskip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PRound::set_has_isskip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PRound::clear_has_isskip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PRound::clear_isskip() {
  isskip_ = false;
  clear_has_isskip();
}
inline bool PRound::isskip() const {
  return isskip_;
}
inline void PRound::set_isskip(bool value) {
  set_has_isskip();
  isskip_ = value;
}

// optional int32 target = 3;
inline bool PRound::has_target() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PRound::set_has_target() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PRound::clear_has_target() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PRound::clear_target() {
  target_ = 0;
  clear_has_target();
}
inline ::google::protobuf::int32 PRound::target() const {
  return target_;
}
inline void PRound::set_target(::google::protobuf::int32 value) {
  set_has_target();
  target_ = value;
}

// repeated .Phurt cards = 4;
inline int PRound::cards_size() const {
  return cards_.size();
}
inline void PRound::clear_cards() {
  cards_.Clear();
}
inline const ::Phurt& PRound::cards(int index) const {
  return cards_.Get(index);
}
inline ::Phurt* PRound::mutable_cards(int index) {
  return cards_.Mutable(index);
}
inline ::Phurt* PRound::add_cards() {
  return cards_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::Phurt >&
PRound::cards() const {
  return cards_;
}
inline ::google::protobuf::RepeatedPtrField< ::Phurt >*
PRound::mutable_cards() {
  return &cards_;
}

// optional int32 aoyiSkillID = 5;
inline bool PRound::has_aoyiskillid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PRound::set_has_aoyiskillid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PRound::clear_has_aoyiskillid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PRound::clear_aoyiskillid() {
  aoyiskillid_ = 0;
  clear_has_aoyiskillid();
}
inline ::google::protobuf::int32 PRound::aoyiskillid() const {
  return aoyiskillid_;
}
inline void PRound::set_aoyiskillid(::google::protobuf::int32 value) {
  set_has_aoyiskillid();
  aoyiskillid_ = value;
}

// repeated string delIcons = 6;
inline int PRound::delicons_size() const {
  return delicons_.size();
}
inline void PRound::clear_delicons() {
  delicons_.Clear();
}
inline const ::std::string& PRound::delicons(int index) const {
  return delicons_.Get(index);
}
inline ::std::string* PRound::mutable_delicons(int index) {
  return delicons_.Mutable(index);
}
inline void PRound::set_delicons(int index, const ::std::string& value) {
  delicons_.Mutable(index)->assign(value);
}
inline void PRound::set_delicons(int index, const char* value) {
  delicons_.Mutable(index)->assign(value);
}
inline void PRound::set_delicons(int index, const char* value, size_t size) {
  delicons_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PRound::add_delicons() {
  return delicons_.Add();
}
inline void PRound::add_delicons(const ::std::string& value) {
  delicons_.Add()->assign(value);
}
inline void PRound::add_delicons(const char* value) {
  delicons_.Add()->assign(value);
}
inline void PRound::add_delicons(const char* value, size_t size) {
  delicons_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PRound::delicons() const {
  return delicons_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PRound::mutable_delicons() {
  return &delicons_;
}

// repeated int32 delStates = 7;
inline int PRound::delstates_size() const {
  return delstates_.size();
}
inline void PRound::clear_delstates() {
  delstates_.Clear();
}
inline ::google::protobuf::int32 PRound::delstates(int index) const {
  return delstates_.Get(index);
}
inline void PRound::set_delstates(int index, ::google::protobuf::int32 value) {
  delstates_.Set(index, value);
}
inline void PRound::add_delstates(::google::protobuf::int32 value) {
  delstates_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PRound::delstates() const {
  return delstates_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PRound::mutable_delstates() {
  return &delstates_;
}

// repeated int32 buffHps = 8;
inline int PRound::buffhps_size() const {
  return buffhps_.size();
}
inline void PRound::clear_buffhps() {
  buffhps_.Clear();
}
inline ::google::protobuf::int32 PRound::buffhps(int index) const {
  return buffhps_.Get(index);
}
inline void PRound::set_buffhps(int index, ::google::protobuf::int32 value) {
  buffhps_.Set(index, value);
}
inline void PRound::add_buffhps(::google::protobuf::int32 value) {
  buffhps_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PRound::buffhps() const {
  return buffhps_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PRound::mutable_buffhps() {
  return &buffhps_;
}

// required int32 leftHp = 9;
inline bool PRound::has_lefthp() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PRound::set_has_lefthp() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PRound::clear_has_lefthp() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PRound::clear_lefthp() {
  lefthp_ = 0;
  clear_has_lefthp();
}
inline ::google::protobuf::int32 PRound::lefthp() const {
  return lefthp_;
}
inline void PRound::set_lefthp(::google::protobuf::int32 value) {
  set_has_lefthp();
  lefthp_ = value;
}

// -------------------------------------------------------------------

// Phurt

// optional int32 card = 1;
inline bool Phurt::has_card() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Phurt::set_has_card() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Phurt::clear_has_card() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Phurt::clear_card() {
  card_ = 0;
  clear_has_card();
}
inline ::google::protobuf::int32 Phurt::card() const {
  return card_;
}
inline void Phurt::set_card(::google::protobuf::int32 value) {
  set_has_card();
  card_ = value;
}

// required bool skillID = 2;
inline bool Phurt::has_skillid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Phurt::set_has_skillid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Phurt::clear_has_skillid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Phurt::clear_skillid() {
  skillid_ = false;
  clear_has_skillid();
}
inline bool Phurt::skillid() const {
  return skillid_;
}
inline void Phurt::set_skillid(bool value) {
  set_has_skillid();
  skillid_ = value;
}

// repeated .PTarget targets = 3;
inline int Phurt::targets_size() const {
  return targets_.size();
}
inline void Phurt::clear_targets() {
  targets_.Clear();
}
inline const ::PTarget& Phurt::targets(int index) const {
  return targets_.Get(index);
}
inline ::PTarget* Phurt::mutable_targets(int index) {
  return targets_.Mutable(index);
}
inline ::PTarget* Phurt::add_targets() {
  return targets_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PTarget >&
Phurt::targets() const {
  return targets_;
}
inline ::google::protobuf::RepeatedPtrField< ::PTarget >*
Phurt::mutable_targets() {
  return &targets_;
}

// -------------------------------------------------------------------

// PTarget

// required int32 targetID = 1;
inline bool PTarget::has_targetid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PTarget::set_has_targetid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PTarget::clear_has_targetid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PTarget::clear_targetid() {
  targetid_ = 0;
  clear_has_targetid();
}
inline ::google::protobuf::int32 PTarget::targetid() const {
  return targetid_;
}
inline void PTarget::set_targetid(::google::protobuf::int32 value) {
  set_has_targetid();
  targetid_ = value;
}

// repeated int32 state = 2;
inline int PTarget::state_size() const {
  return state_.size();
}
inline void PTarget::clear_state() {
  state_.Clear();
}
inline ::google::protobuf::int32 PTarget::state(int index) const {
  return state_.Get(index);
}
inline void PTarget::set_state(int index, ::google::protobuf::int32 value) {
  state_.Set(index, value);
}
inline void PTarget::add_state(::google::protobuf::int32 value) {
  state_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PTarget::state() const {
  return state_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PTarget::mutable_state() {
  return &state_;
}

// repeated string buffIcon = 3;
inline int PTarget::bufficon_size() const {
  return bufficon_.size();
}
inline void PTarget::clear_bufficon() {
  bufficon_.Clear();
}
inline const ::std::string& PTarget::bufficon(int index) const {
  return bufficon_.Get(index);
}
inline ::std::string* PTarget::mutable_bufficon(int index) {
  return bufficon_.Mutable(index);
}
inline void PTarget::set_bufficon(int index, const ::std::string& value) {
  bufficon_.Mutable(index)->assign(value);
}
inline void PTarget::set_bufficon(int index, const char* value) {
  bufficon_.Mutable(index)->assign(value);
}
inline void PTarget::set_bufficon(int index, const char* value, size_t size) {
  bufficon_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PTarget::add_bufficon() {
  return bufficon_.Add();
}
inline void PTarget::add_bufficon(const ::std::string& value) {
  bufficon_.Add()->assign(value);
}
inline void PTarget::add_bufficon(const char* value) {
  bufficon_.Add()->assign(value);
}
inline void PTarget::add_bufficon(const char* value, size_t size) {
  bufficon_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PTarget::bufficon() const {
  return bufficon_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PTarget::mutable_bufficon() {
  return &bufficon_;
}

// required int32 hp = 4;
inline bool PTarget::has_hp() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PTarget::set_has_hp() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PTarget::clear_has_hp() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PTarget::clear_hp() {
  hp_ = 0;
  clear_has_hp();
}
inline ::google::protobuf::int32 PTarget::hp() const {
  return hp_;
}
inline void PTarget::set_hp(::google::protobuf::int32 value) {
  set_has_hp();
  hp_ = value;
}

// required int32 leftHp = 5;
inline bool PTarget::has_lefthp() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PTarget::set_has_lefthp() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PTarget::clear_has_lefthp() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PTarget::clear_lefthp() {
  lefthp_ = 0;
  clear_has_lefthp();
}
inline ::google::protobuf::int32 PTarget::lefthp() const {
  return lefthp_;
}
inline void PTarget::set_lefthp(::google::protobuf::int32 value) {
  set_has_lefthp();
  lefthp_ = value;
}

// required int32 hpTypes = 6;
inline bool PTarget::has_hptypes() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PTarget::set_has_hptypes() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PTarget::clear_has_hptypes() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PTarget::clear_hptypes() {
  hptypes_ = 0;
  clear_has_hptypes();
}
inline ::google::protobuf::int32 PTarget::hptypes() const {
  return hptypes_;
}
inline void PTarget::set_hptypes(::google::protobuf::int32 value) {
  set_has_hptypes();
  hptypes_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_battle_2eproto__INCLUDED
