// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: battle.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "battle.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PBattle_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PBattle_reflection_ = NULL;
const ::google::protobuf::Descriptor* PFightItem_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PFightItem_reflection_ = NULL;
const ::google::protobuf::Descriptor* PRound_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PRound_reflection_ = NULL;
const ::google::protobuf::Descriptor* Phurt_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Phurt_reflection_ = NULL;
const ::google::protobuf::Descriptor* PTarget_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PTarget_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_battle_2eproto() {
  protobuf_AddDesc_battle_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "battle.proto");
  GOOGLE_CHECK(file != NULL);
  PBattle_descriptor_ = file->message_type(0);
  static const int PBattle_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, heros_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, rounds_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, cards_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, gold_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, winnerid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, type_),
  };
  PBattle_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PBattle_descriptor_,
      PBattle::default_instance_,
      PBattle_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PBattle, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PBattle));
  PFightItem_descriptor_ = file->message_type(1);
  static const int PFightItem_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, hp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, xid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, friendid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, friendname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, friendxid_),
  };
  PFightItem_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PFightItem_descriptor_,
      PFightItem::default_instance_,
      PFightItem_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PFightItem, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PFightItem));
  PRound_descriptor_ = file->message_type(2);
  static const int PRound_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, source_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, isskip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, cards_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, aoyiskillid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, lefticons_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, leftstates_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, buffhps_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, lefthp_),
  };
  PRound_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PRound_descriptor_,
      PRound::default_instance_,
      PRound_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PRound, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PRound));
  Phurt_descriptor_ = file->message_type(3);
  static const int Phurt_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, card_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, skillid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, targets_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, level_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, star_),
  };
  Phurt_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Phurt_descriptor_,
      Phurt::default_instance_,
      Phurt_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Phurt, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Phurt));
  PTarget_descriptor_ = file->message_type(4);
  static const int PTarget_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, targetid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, bufficon_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, hp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, lefthp_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, hptypes_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, skillid_),
  };
  PTarget_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PTarget_descriptor_,
      PTarget::default_instance_,
      PTarget_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PTarget, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PTarget));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_battle_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PBattle_descriptor_, &PBattle::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PFightItem_descriptor_, &PFightItem::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PRound_descriptor_, &PRound::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Phurt_descriptor_, &Phurt::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PTarget_descriptor_, &PTarget::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_battle_2eproto() {
  delete PBattle::default_instance_;
  delete PBattle_reflection_;
  delete PFightItem::default_instance_;
  delete PFightItem_reflection_;
  delete PRound::default_instance_;
  delete PRound_reflection_;
  delete Phurt::default_instance_;
  delete Phurt_reflection_;
  delete PTarget::default_instance_;
  delete PTarget_reflection_;
}

void protobuf_AddDesc_battle_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\014battle.proto\"{\n\007PBattle\022\032\n\005heros\030\001 \003(\013"
    "2\013.PFightItem\022\027\n\006rounds\030\002 \003(\0132\007.PRound\022\r"
    "\n\005cards\030\003 \003(\005\022\014\n\004gold\030\004 \002(\005\022\020\n\010winnerID\030"
    "\005 \002(\003\022\014\n\004type\030\006 \002(\005\"x\n\nPFightItem\022\n\n\002id\030"
    "\001 \002(\003\022\n\n\002hp\030\002 \002(\005\022\014\n\004name\030\003 \002(\t\022\013\n\003xid\030\004"
    " \002(\005\022\020\n\010friendID\030\005 \002(\003\022\022\n\nfriendName\030\006 \002"
    "(\t\022\021\n\tfriendXid\030\007 \002(\005\"\234\001\n\006PRound\022\016\n\006sour"
    "ce\030\001 \002(\005\022\016\n\006isSkip\030\002 \002(\010\022\025\n\005cards\030\003 \003(\0132"
    "\006.Phurt\022\023\n\013aoyiSkillID\030\004 \001(\005\022\021\n\tleftIcon"
    "s\030\005 \003(\t\022\022\n\nleftStates\030\006 \003(\005\022\017\n\007buffHps\030\007"
    " \003(\005\022\016\n\006leftHp\030\010 \002(\005\"^\n\005Phurt\022\014\n\004card\030\001 "
    "\001(\005\022\017\n\007skillID\030\002 \002(\010\022\031\n\007targets\030\003 \003(\0132\010."
    "PTarget\022\r\n\005level\030\004 \001(\005\022\014\n\004star\030\005 \001(\005\"z\n\007"
    "PTarget\022\020\n\010targetID\030\001 \002(\005\022\r\n\005state\030\002 \003(\005"
    "\022\020\n\010buffIcon\030\003 \003(\t\022\n\n\002hp\030\004 \002(\005\022\016\n\006leftHp"
    "\030\005 \002(\005\022\017\n\007hpTypes\030\006 \002(\005\022\017\n\007skillID\030\007 \002(\005", 640);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "battle.proto", &protobuf_RegisterTypes);
  PBattle::default_instance_ = new PBattle();
  PFightItem::default_instance_ = new PFightItem();
  PRound::default_instance_ = new PRound();
  Phurt::default_instance_ = new Phurt();
  PTarget::default_instance_ = new PTarget();
  PBattle::default_instance_->InitAsDefaultInstance();
  PFightItem::default_instance_->InitAsDefaultInstance();
  PRound::default_instance_->InitAsDefaultInstance();
  Phurt::default_instance_->InitAsDefaultInstance();
  PTarget::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_battle_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_battle_2eproto {
  StaticDescriptorInitializer_battle_2eproto() {
    protobuf_AddDesc_battle_2eproto();
  }
} static_descriptor_initializer_battle_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PBattle::kHerosFieldNumber;
const int PBattle::kRoundsFieldNumber;
const int PBattle::kCardsFieldNumber;
const int PBattle::kGoldFieldNumber;
const int PBattle::kWinnerIDFieldNumber;
const int PBattle::kTypeFieldNumber;
#endif  // !_MSC_VER

PBattle::PBattle()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PBattle::InitAsDefaultInstance() {
}

PBattle::PBattle(const PBattle& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PBattle::SharedCtor() {
  _cached_size_ = 0;
  gold_ = 0;
  winnerid_ = GOOGLE_LONGLONG(0);
  type_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PBattle::~PBattle() {
  SharedDtor();
}

void PBattle::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PBattle::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PBattle::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PBattle_descriptor_;
}

const PBattle& PBattle::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PBattle* PBattle::default_instance_ = NULL;

PBattle* PBattle::New() const {
  return new PBattle;
}

void PBattle::Clear() {
  if (_has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    gold_ = 0;
    winnerid_ = GOOGLE_LONGLONG(0);
    type_ = 0;
  }
  heros_.Clear();
  rounds_.Clear();
  cards_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PBattle::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .PFightItem heros = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_heros:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_heros()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_heros;
        if (input->ExpectTag(18)) goto parse_rounds;
        break;
      }

      // repeated .PRound rounds = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_rounds:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_rounds()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_rounds;
        if (input->ExpectTag(24)) goto parse_cards;
        break;
      }

      // repeated int32 cards = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_cards:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 24, input, this->mutable_cards())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_cards())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_cards;
        if (input->ExpectTag(32)) goto parse_gold;
        break;
      }

      // required int32 gold = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_gold:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &gold_)));
          set_has_gold();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_winnerID;
        break;
      }

      // required int64 winnerID = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_winnerID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &winnerid_)));
          set_has_winnerid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_type;
        break;
      }

      // required int32 type = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_type:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PBattle::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .PFightItem heros = 1;
  for (int i = 0; i < this->heros_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->heros(i), output);
  }

  // repeated .PRound rounds = 2;
  for (int i = 0; i < this->rounds_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->rounds(i), output);
  }

  // repeated int32 cards = 3;
  for (int i = 0; i < this->cards_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      3, this->cards(i), output);
  }

  // required int32 gold = 4;
  if (has_gold()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->gold(), output);
  }

  // required int64 winnerID = 5;
  if (has_winnerid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->winnerid(), output);
  }

  // required int32 type = 6;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PBattle::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .PFightItem heros = 1;
  for (int i = 0; i < this->heros_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->heros(i), target);
  }

  // repeated .PRound rounds = 2;
  for (int i = 0; i < this->rounds_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->rounds(i), target);
  }

  // repeated int32 cards = 3;
  for (int i = 0; i < this->cards_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(3, this->cards(i), target);
  }

  // required int32 gold = 4;
  if (has_gold()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->gold(), target);
  }

  // required int64 winnerID = 5;
  if (has_winnerid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->winnerid(), target);
  }

  // required int32 type = 6;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PBattle::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    // required int32 gold = 4;
    if (has_gold()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->gold());
    }

    // required int64 winnerID = 5;
    if (has_winnerid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->winnerid());
    }

    // required int32 type = 6;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

  }
  // repeated .PFightItem heros = 1;
  total_size += 1 * this->heros_size();
  for (int i = 0; i < this->heros_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->heros(i));
  }

  // repeated .PRound rounds = 2;
  total_size += 1 * this->rounds_size();
  for (int i = 0; i < this->rounds_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->rounds(i));
  }

  // repeated int32 cards = 3;
  {
    int data_size = 0;
    for (int i = 0; i < this->cards_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->cards(i));
    }
    total_size += 1 * this->cards_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PBattle::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PBattle* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PBattle*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PBattle::MergeFrom(const PBattle& from) {
  GOOGLE_CHECK_NE(&from, this);
  heros_.MergeFrom(from.heros_);
  rounds_.MergeFrom(from.rounds_);
  cards_.MergeFrom(from.cards_);
  if (from._has_bits_[3 / 32] & (0xffu << (3 % 32))) {
    if (from.has_gold()) {
      set_gold(from.gold());
    }
    if (from.has_winnerid()) {
      set_winnerid(from.winnerid());
    }
    if (from.has_type()) {
      set_type(from.type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PBattle::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBattle::CopyFrom(const PBattle& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBattle::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000038) != 0x00000038) return false;

  for (int i = 0; i < heros_size(); i++) {
    if (!this->heros(i).IsInitialized()) return false;
  }
  for (int i = 0; i < rounds_size(); i++) {
    if (!this->rounds(i).IsInitialized()) return false;
  }
  return true;
}

void PBattle::Swap(PBattle* other) {
  if (other != this) {
    heros_.Swap(&other->heros_);
    rounds_.Swap(&other->rounds_);
    cards_.Swap(&other->cards_);
    std::swap(gold_, other->gold_);
    std::swap(winnerid_, other->winnerid_);
    std::swap(type_, other->type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PBattle::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PBattle_descriptor_;
  metadata.reflection = PBattle_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PFightItem::kIdFieldNumber;
const int PFightItem::kHpFieldNumber;
const int PFightItem::kNameFieldNumber;
const int PFightItem::kXidFieldNumber;
const int PFightItem::kFriendIDFieldNumber;
const int PFightItem::kFriendNameFieldNumber;
const int PFightItem::kFriendXidFieldNumber;
#endif  // !_MSC_VER

PFightItem::PFightItem()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PFightItem::InitAsDefaultInstance() {
}

PFightItem::PFightItem(const PFightItem& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PFightItem::SharedCtor() {
  _cached_size_ = 0;
  id_ = GOOGLE_LONGLONG(0);
  hp_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  xid_ = 0;
  friendid_ = GOOGLE_LONGLONG(0);
  friendname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  friendxid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PFightItem::~PFightItem() {
  SharedDtor();
}

void PFightItem::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (friendname_ != &::google::protobuf::internal::kEmptyString) {
    delete friendname_;
  }
  if (this != default_instance_) {
  }
}

void PFightItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PFightItem::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PFightItem_descriptor_;
}

const PFightItem& PFightItem::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PFightItem* PFightItem::default_instance_ = NULL;

PFightItem* PFightItem::New() const {
  return new PFightItem;
}

void PFightItem::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = GOOGLE_LONGLONG(0);
    hp_ = 0;
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    xid_ = 0;
    friendid_ = GOOGLE_LONGLONG(0);
    if (has_friendname()) {
      if (friendname_ != &::google::protobuf::internal::kEmptyString) {
        friendname_->clear();
      }
    }
    friendxid_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PFightItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_hp;
        break;
      }

      // required int32 hp = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hp_)));
          set_has_hp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_name;
        break;
      }

      // required string name = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_xid;
        break;
      }

      // required int32 xid = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_xid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &xid_)));
          set_has_xid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_friendID;
        break;
      }

      // required int64 friendID = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_friendID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &friendid_)));
          set_has_friendid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_friendName;
        break;
      }

      // required string friendName = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_friendName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_friendname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->friendname().data(), this->friendname().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_friendXid;
        break;
      }

      // required int32 friendXid = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_friendXid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &friendxid_)));
          set_has_friendxid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PFightItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  // required int32 hp = 2;
  if (has_hp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->hp(), output);
  }

  // required string name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->name(), output);
  }

  // required int32 xid = 4;
  if (has_xid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->xid(), output);
  }

  // required int64 friendID = 5;
  if (has_friendid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(5, this->friendid(), output);
  }

  // required string friendName = 6;
  if (has_friendname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->friendname().data(), this->friendname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->friendname(), output);
  }

  // required int32 friendXid = 7;
  if (has_friendxid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->friendxid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PFightItem::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int64 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  // required int32 hp = 2;
  if (has_hp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->hp(), target);
  }

  // required string name = 3;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // required int32 xid = 4;
  if (has_xid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->xid(), target);
  }

  // required int64 friendID = 5;
  if (has_friendid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(5, this->friendid(), target);
  }

  // required string friendName = 6;
  if (has_friendname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->friendname().data(), this->friendname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->friendname(), target);
  }

  // required int32 friendXid = 7;
  if (has_friendxid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->friendxid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PFightItem::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int64 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->id());
    }

    // required int32 hp = 2;
    if (has_hp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->hp());
    }

    // required string name = 3;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // required int32 xid = 4;
    if (has_xid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->xid());
    }

    // required int64 friendID = 5;
    if (has_friendid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->friendid());
    }

    // required string friendName = 6;
    if (has_friendname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->friendname());
    }

    // required int32 friendXid = 7;
    if (has_friendxid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->friendxid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PFightItem::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PFightItem* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PFightItem*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PFightItem::MergeFrom(const PFightItem& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_hp()) {
      set_hp(from.hp());
    }
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_xid()) {
      set_xid(from.xid());
    }
    if (from.has_friendid()) {
      set_friendid(from.friendid());
    }
    if (from.has_friendname()) {
      set_friendname(from.friendname());
    }
    if (from.has_friendxid()) {
      set_friendxid(from.friendxid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PFightItem::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PFightItem::CopyFrom(const PFightItem& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PFightItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  return true;
}

void PFightItem::Swap(PFightItem* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(hp_, other->hp_);
    std::swap(name_, other->name_);
    std::swap(xid_, other->xid_);
    std::swap(friendid_, other->friendid_);
    std::swap(friendname_, other->friendname_);
    std::swap(friendxid_, other->friendxid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PFightItem::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PFightItem_descriptor_;
  metadata.reflection = PFightItem_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PRound::kSourceFieldNumber;
const int PRound::kIsSkipFieldNumber;
const int PRound::kCardsFieldNumber;
const int PRound::kAoyiSkillIDFieldNumber;
const int PRound::kLeftIconsFieldNumber;
const int PRound::kLeftStatesFieldNumber;
const int PRound::kBuffHpsFieldNumber;
const int PRound::kLeftHpFieldNumber;
#endif  // !_MSC_VER

PRound::PRound()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PRound::InitAsDefaultInstance() {
}

PRound::PRound(const PRound& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PRound::SharedCtor() {
  _cached_size_ = 0;
  source_ = 0;
  isskip_ = false;
  aoyiskillid_ = 0;
  lefthp_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PRound::~PRound() {
  SharedDtor();
}

void PRound::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PRound::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PRound::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PRound_descriptor_;
}

const PRound& PRound::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PRound* PRound::default_instance_ = NULL;

PRound* PRound::New() const {
  return new PRound;
}

void PRound::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    source_ = 0;
    isskip_ = false;
    aoyiskillid_ = 0;
    lefthp_ = 0;
  }
  cards_.Clear();
  lefticons_.Clear();
  leftstates_.Clear();
  buffhps_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PRound::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 source = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &source_)));
          set_has_source();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_isSkip;
        break;
      }

      // required bool isSkip = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_isSkip:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isskip_)));
          set_has_isskip();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_cards;
        break;
      }

      // repeated .Phurt cards = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_cards:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_cards()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_cards;
        if (input->ExpectTag(32)) goto parse_aoyiSkillID;
        break;
      }

      // optional int32 aoyiSkillID = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_aoyiSkillID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &aoyiskillid_)));
          set_has_aoyiskillid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_leftIcons;
        break;
      }

      // repeated string leftIcons = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_leftIcons:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_lefticons()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->lefticons(this->lefticons_size() - 1).data(),
            this->lefticons(this->lefticons_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(42)) goto parse_leftIcons;
        if (input->ExpectTag(48)) goto parse_leftStates;
        break;
      }

      // repeated int32 leftStates = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_leftStates:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48, input, this->mutable_leftstates())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_leftstates())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_leftStates;
        if (input->ExpectTag(56)) goto parse_buffHps;
        break;
      }

      // repeated int32 buffHps = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_buffHps:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 56, input, this->mutable_buffhps())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_buffhps())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_buffHps;
        if (input->ExpectTag(64)) goto parse_leftHp;
        break;
      }

      // required int32 leftHp = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_leftHp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &lefthp_)));
          set_has_lefthp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PRound::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 source = 1;
  if (has_source()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->source(), output);
  }

  // required bool isSkip = 2;
  if (has_isskip()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->isskip(), output);
  }

  // repeated .Phurt cards = 3;
  for (int i = 0; i < this->cards_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->cards(i), output);
  }

  // optional int32 aoyiSkillID = 4;
  if (has_aoyiskillid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->aoyiskillid(), output);
  }

  // repeated string leftIcons = 5;
  for (int i = 0; i < this->lefticons_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->lefticons(i).data(), this->lefticons(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      5, this->lefticons(i), output);
  }

  // repeated int32 leftStates = 6;
  for (int i = 0; i < this->leftstates_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->leftstates(i), output);
  }

  // repeated int32 buffHps = 7;
  for (int i = 0; i < this->buffhps_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      7, this->buffhps(i), output);
  }

  // required int32 leftHp = 8;
  if (has_lefthp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->lefthp(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PRound::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 source = 1;
  if (has_source()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->source(), target);
  }

  // required bool isSkip = 2;
  if (has_isskip()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->isskip(), target);
  }

  // repeated .Phurt cards = 3;
  for (int i = 0; i < this->cards_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->cards(i), target);
  }

  // optional int32 aoyiSkillID = 4;
  if (has_aoyiskillid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->aoyiskillid(), target);
  }

  // repeated string leftIcons = 5;
  for (int i = 0; i < this->lefticons_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->lefticons(i).data(), this->lefticons(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(5, this->lefticons(i), target);
  }

  // repeated int32 leftStates = 6;
  for (int i = 0; i < this->leftstates_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(6, this->leftstates(i), target);
  }

  // repeated int32 buffHps = 7;
  for (int i = 0; i < this->buffhps_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(7, this->buffhps(i), target);
  }

  // required int32 leftHp = 8;
  if (has_lefthp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->lefthp(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PRound::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 source = 1;
    if (has_source()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->source());
    }

    // required bool isSkip = 2;
    if (has_isskip()) {
      total_size += 1 + 1;
    }

    // optional int32 aoyiSkillID = 4;
    if (has_aoyiskillid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->aoyiskillid());
    }

    // required int32 leftHp = 8;
    if (has_lefthp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->lefthp());
    }

  }
  // repeated .Phurt cards = 3;
  total_size += 1 * this->cards_size();
  for (int i = 0; i < this->cards_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->cards(i));
  }

  // repeated string leftIcons = 5;
  total_size += 1 * this->lefticons_size();
  for (int i = 0; i < this->lefticons_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->lefticons(i));
  }

  // repeated int32 leftStates = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->leftstates_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->leftstates(i));
    }
    total_size += 1 * this->leftstates_size() + data_size;
  }

  // repeated int32 buffHps = 7;
  {
    int data_size = 0;
    for (int i = 0; i < this->buffhps_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->buffhps(i));
    }
    total_size += 1 * this->buffhps_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PRound::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PRound* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PRound*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PRound::MergeFrom(const PRound& from) {
  GOOGLE_CHECK_NE(&from, this);
  cards_.MergeFrom(from.cards_);
  lefticons_.MergeFrom(from.lefticons_);
  leftstates_.MergeFrom(from.leftstates_);
  buffhps_.MergeFrom(from.buffhps_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_source()) {
      set_source(from.source());
    }
    if (from.has_isskip()) {
      set_isskip(from.isskip());
    }
    if (from.has_aoyiskillid()) {
      set_aoyiskillid(from.aoyiskillid());
    }
    if (from.has_lefthp()) {
      set_lefthp(from.lefthp());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PRound::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PRound::CopyFrom(const PRound& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PRound::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000083) != 0x00000083) return false;

  for (int i = 0; i < cards_size(); i++) {
    if (!this->cards(i).IsInitialized()) return false;
  }
  return true;
}

void PRound::Swap(PRound* other) {
  if (other != this) {
    std::swap(source_, other->source_);
    std::swap(isskip_, other->isskip_);
    cards_.Swap(&other->cards_);
    std::swap(aoyiskillid_, other->aoyiskillid_);
    lefticons_.Swap(&other->lefticons_);
    leftstates_.Swap(&other->leftstates_);
    buffhps_.Swap(&other->buffhps_);
    std::swap(lefthp_, other->lefthp_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PRound::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PRound_descriptor_;
  metadata.reflection = PRound_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Phurt::kCardFieldNumber;
const int Phurt::kSkillIDFieldNumber;
const int Phurt::kTargetsFieldNumber;
const int Phurt::kLevelFieldNumber;
const int Phurt::kStarFieldNumber;
#endif  // !_MSC_VER

Phurt::Phurt()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Phurt::InitAsDefaultInstance() {
}

Phurt::Phurt(const Phurt& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Phurt::SharedCtor() {
  _cached_size_ = 0;
  card_ = 0;
  skillid_ = false;
  level_ = 0;
  star_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Phurt::~Phurt() {
  SharedDtor();
}

void Phurt::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Phurt::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Phurt::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Phurt_descriptor_;
}

const Phurt& Phurt::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

Phurt* Phurt::default_instance_ = NULL;

Phurt* Phurt::New() const {
  return new Phurt;
}

void Phurt::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    card_ = 0;
    skillid_ = false;
    level_ = 0;
    star_ = 0;
  }
  targets_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Phurt::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 card = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &card_)));
          set_has_card();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_skillID;
        break;
      }

      // required bool skillID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_skillID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &skillid_)));
          set_has_skillid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_targets;
        break;
      }

      // repeated .PTarget targets = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_targets:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_targets()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_targets;
        if (input->ExpectTag(32)) goto parse_level;
        break;
      }

      // optional int32 level = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_level:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &level_)));
          set_has_level();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_star;
        break;
      }

      // optional int32 star = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_star:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &star_)));
          set_has_star();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Phurt::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional int32 card = 1;
  if (has_card()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->card(), output);
  }

  // required bool skillID = 2;
  if (has_skillid()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->skillid(), output);
  }

  // repeated .PTarget targets = 3;
  for (int i = 0; i < this->targets_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->targets(i), output);
  }

  // optional int32 level = 4;
  if (has_level()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->level(), output);
  }

  // optional int32 star = 5;
  if (has_star()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->star(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Phurt::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional int32 card = 1;
  if (has_card()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->card(), target);
  }

  // required bool skillID = 2;
  if (has_skillid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->skillid(), target);
  }

  // repeated .PTarget targets = 3;
  for (int i = 0; i < this->targets_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, this->targets(i), target);
  }

  // optional int32 level = 4;
  if (has_level()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->level(), target);
  }

  // optional int32 star = 5;
  if (has_star()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->star(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Phurt::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 card = 1;
    if (has_card()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->card());
    }

    // required bool skillID = 2;
    if (has_skillid()) {
      total_size += 1 + 1;
    }

    // optional int32 level = 4;
    if (has_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->level());
    }

    // optional int32 star = 5;
    if (has_star()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->star());
    }

  }
  // repeated .PTarget targets = 3;
  total_size += 1 * this->targets_size();
  for (int i = 0; i < this->targets_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->targets(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Phurt::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Phurt* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Phurt*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Phurt::MergeFrom(const Phurt& from) {
  GOOGLE_CHECK_NE(&from, this);
  targets_.MergeFrom(from.targets_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_card()) {
      set_card(from.card());
    }
    if (from.has_skillid()) {
      set_skillid(from.skillid());
    }
    if (from.has_level()) {
      set_level(from.level());
    }
    if (from.has_star()) {
      set_star(from.star());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Phurt::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Phurt::CopyFrom(const Phurt& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Phurt::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000002) != 0x00000002) return false;

  for (int i = 0; i < targets_size(); i++) {
    if (!this->targets(i).IsInitialized()) return false;
  }
  return true;
}

void Phurt::Swap(Phurt* other) {
  if (other != this) {
    std::swap(card_, other->card_);
    std::swap(skillid_, other->skillid_);
    targets_.Swap(&other->targets_);
    std::swap(level_, other->level_);
    std::swap(star_, other->star_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Phurt::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Phurt_descriptor_;
  metadata.reflection = Phurt_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int PTarget::kTargetIDFieldNumber;
const int PTarget::kStateFieldNumber;
const int PTarget::kBuffIconFieldNumber;
const int PTarget::kHpFieldNumber;
const int PTarget::kLeftHpFieldNumber;
const int PTarget::kHpTypesFieldNumber;
const int PTarget::kSkillIDFieldNumber;
#endif  // !_MSC_VER

PTarget::PTarget()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PTarget::InitAsDefaultInstance() {
}

PTarget::PTarget(const PTarget& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PTarget::SharedCtor() {
  _cached_size_ = 0;
  targetid_ = 0;
  hp_ = 0;
  lefthp_ = 0;
  hptypes_ = 0;
  skillid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PTarget::~PTarget() {
  SharedDtor();
}

void PTarget::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PTarget::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PTarget::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PTarget_descriptor_;
}

const PTarget& PTarget::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_battle_2eproto();
  return *default_instance_;
}

PTarget* PTarget::default_instance_ = NULL;

PTarget* PTarget::New() const {
  return new PTarget;
}

void PTarget::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    targetid_ = 0;
    hp_ = 0;
    lefthp_ = 0;
    hptypes_ = 0;
    skillid_ = 0;
  }
  state_.Clear();
  bufficon_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PTarget::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 targetID = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &targetid_)));
          set_has_targetid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_state;
        break;
      }

      // repeated int32 state = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_state:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 16, input, this->mutable_state())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_state())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_state;
        if (input->ExpectTag(26)) goto parse_buffIcon;
        break;
      }

      // repeated string buffIcon = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_buffIcon:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_bufficon()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->bufficon(this->bufficon_size() - 1).data(),
            this->bufficon(this->bufficon_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_buffIcon;
        if (input->ExpectTag(32)) goto parse_hp;
        break;
      }

      // required int32 hp = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hp_)));
          set_has_hp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_leftHp;
        break;
      }

      // required int32 leftHp = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_leftHp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &lefthp_)));
          set_has_lefthp();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_hpTypes;
        break;
      }

      // required int32 hpTypes = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hpTypes:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &hptypes_)));
          set_has_hptypes();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_skillID;
        break;
      }

      // required int32 skillID = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_skillID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &skillid_)));
          set_has_skillid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void PTarget::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 targetID = 1;
  if (has_targetid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->targetid(), output);
  }

  // repeated int32 state = 2;
  for (int i = 0; i < this->state_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      2, this->state(i), output);
  }

  // repeated string buffIcon = 3;
  for (int i = 0; i < this->bufficon_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->bufficon(i).data(), this->bufficon(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->bufficon(i), output);
  }

  // required int32 hp = 4;
  if (has_hp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->hp(), output);
  }

  // required int32 leftHp = 5;
  if (has_lefthp()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->lefthp(), output);
  }

  // required int32 hpTypes = 6;
  if (has_hptypes()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->hptypes(), output);
  }

  // required int32 skillID = 7;
  if (has_skillid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->skillid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PTarget::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 targetID = 1;
  if (has_targetid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->targetid(), target);
  }

  // repeated int32 state = 2;
  for (int i = 0; i < this->state_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(2, this->state(i), target);
  }

  // repeated string buffIcon = 3;
  for (int i = 0; i < this->bufficon_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->bufficon(i).data(), this->bufficon(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->bufficon(i), target);
  }

  // required int32 hp = 4;
  if (has_hp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->hp(), target);
  }

  // required int32 leftHp = 5;
  if (has_lefthp()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->lefthp(), target);
  }

  // required int32 hpTypes = 6;
  if (has_hptypes()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->hptypes(), target);
  }

  // required int32 skillID = 7;
  if (has_skillid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->skillid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PTarget::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 targetID = 1;
    if (has_targetid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->targetid());
    }

    // required int32 hp = 4;
    if (has_hp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->hp());
    }

    // required int32 leftHp = 5;
    if (has_lefthp()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->lefthp());
    }

    // required int32 hpTypes = 6;
    if (has_hptypes()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->hptypes());
    }

    // required int32 skillID = 7;
    if (has_skillid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->skillid());
    }

  }
  // repeated int32 state = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->state_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->state(i));
    }
    total_size += 1 * this->state_size() + data_size;
  }

  // repeated string buffIcon = 3;
  total_size += 1 * this->bufficon_size();
  for (int i = 0; i < this->bufficon_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->bufficon(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PTarget::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PTarget* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PTarget*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PTarget::MergeFrom(const PTarget& from) {
  GOOGLE_CHECK_NE(&from, this);
  state_.MergeFrom(from.state_);
  bufficon_.MergeFrom(from.bufficon_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_targetid()) {
      set_targetid(from.targetid());
    }
    if (from.has_hp()) {
      set_hp(from.hp());
    }
    if (from.has_lefthp()) {
      set_lefthp(from.lefthp());
    }
    if (from.has_hptypes()) {
      set_hptypes(from.hptypes());
    }
    if (from.has_skillid()) {
      set_skillid(from.skillid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PTarget::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PTarget::CopyFrom(const PTarget& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PTarget::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000079) != 0x00000079) return false;

  return true;
}

void PTarget::Swap(PTarget* other) {
  if (other != this) {
    std::swap(targetid_, other->targetid_);
    state_.Swap(&other->state_);
    bufficon_.Swap(&other->bufficon_);
    std::swap(hp_, other->hp_);
    std::swap(lefthp_, other->lefthp_);
    std::swap(hptypes_, other->hptypes_);
    std::swap(skillid_, other->skillid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PTarget::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PTarget_descriptor_;
  metadata.reflection = PTarget_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
